In [63]:
#   导入语句。
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
# np.set_printoptions(suppress=True,threshold=np.nan)
#提出问题：你应该在你的调查里分析至少一个因变量和三个自变量。每年最受欢迎的电影类别是哪些？票房高的电影有哪些特点？
#预算，人员（演员、导演）、类别、上映月份，与净利润的关系 
#1，预算与净利润之间有什么关系？（预算与净利润之间的关系比较，散点图，计算相关性，必要时画出其回归线）
#2，top10的演员是谁，各种电影类别对应的票房？（每个演员、导演、类别对应净利润的平均值之间比较，画bar图）  
#3，上映月份与净利润有何关系？（画出对应每个月份利润平均值，进行比较，用bar图）

In [2]:
df = pd.read_csv('tmdb-movies.csv')
df.head(1)

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/15,5562,6.5,2015,1.379999e+08,1.392446e+09

In [3]:
df.columns

Index(['id', 'imdb_id', 'popularity', 'budget', 'revenue', 'original_title',
       'cast', 'homepage', 'director', 'tagline', 'keywords', 'overview',
       'runtime', 'genres', 'production_companies', 'release_date',
       'vote_count', 'vote_average', 'release_year', 'budget_adj',
       'revenue_adj'],
      dtype='object')

In [64]:
df = df.drop(['id','imdb_id','revenue','popularity','homepage','tagline','overview','release_year'],axis=1)
df.head(1)

KeyError: "['id' 'imdb_id' 'revenue' 'popularity' 'homepage' 'tagline' 'overview'\n 'release_year'] not found in axis"

In [65]:
df['profit'] = df['revenue_adj'] - df['budget_adj']

KeyError: 'revenue_adj'

In [66]:
df.head(1)

,original_title,cast,director,keywords,runtime,genres,production_companies,release_date,vote_count,vote_average,profit,month
0,Ronaldo,Cristiano Ronaldo,Anthony Wonke,biography|soccer player,0,Documentary,"On The Corner Films|We Came, We Saw, We Conque...",11/9/15,80,6.5,0.0,11

In [7]:
df = df.drop(['budget_adj','revenue_adj'], axis =1)

In [8]:
df.head(1)

,original_title,cast,director,keywords,runtime,genres,production_companies,release_date,vote_count,vote_average,profit
0,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,monster|dna|tyrannosaurus rex|velociraptor|island,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/15,5562,6.5,1.254446e+09

In [9]:
df['cast'].iloc[0].count('|')

4

In [10]:
df['cast'].shape

(10866,)

In [11]:
df1 = df.copy()
df2 = df.copy()
df3 = df.copy()
df4 = df.copy()
df5 = df.copy()

In [12]:
split_columns = ['cast','genres']

In [13]:
total_rows = df['cast'].shape[0]

In [14]:
#计算演员一栏中，每个元素里还有几个”|“
cast_counts = []
for i in range(total_rows):
    num_1 = df['cast'].astype(str).iloc[i].count('|')
    cast_counts.append(num_1)

In [15]:
set(cast_counts)

{0, 1, 2, 3, 4}

In [16]:
cast_counts.count(4)

10134

In [17]:
df.isnull().sum()

original_title             0
cast                      76
director                  44
keywords                1493
runtime                    0
genres                    23
production_companies    1030
release_date               0
vote_count                 0
vote_average               0
profit                     0
dtype: int64

In [18]:
df = df.fillna('')

In [19]:
df['cast_counts'] = cast_counts  #添加一列cast_counts，表示cast中有几个|

In [50]:
df_ctn0 = df.query('cast_counts == 0')
df_plus0 = df_ctn0

In [51]:
df_ctn1 = df.query('cast_counts == 1')
df_ctn11 = df_ctn1.copy()
df_ctn12 = df_ctn1.copy()

In [52]:
df_ctn11['cast'] = df_ctn11['cast'].astype(str).apply(lambda x: x.split('|')[0])
df_ctn12['cast'] = df_ctn12['cast'].astype(str).apply(lambda x: x.split('|')[1])
df_plus1 =df_ctn11.append(df_ctn12)

IndexError: list index out of range

In [53]:
df_ctn2 = df.query('cast_counts == 2')
df_ctn21 = df_ctn2.copy()
df_ctn22 = df_ctn2.copy()
df_ctn23 = df_ctn2.copy()
df_ctn21['cast'] = df_ctn21['cast'].astype(str).apply(lambda x: x.split('|')[0])
df_ctn22['cast'] = df_ctn22['cast'].astype(str).apply(lambda x: x.split('|')[1])
df_ctn23['cast'] = df_ctn23['cast'].astype(str).apply(lambda x: x.split('|')[2])
df_plus2 =df_ctn21.append(df_ctn22).append(df_ctn23)

IndexError: list index out of range

In [24]:
df_ctn3 = df.query('cast_counts == 3')
df_ctn31 = df_ctn3.copy()
df_ctn32 = df_ctn3.copy()
df_ctn33 = df_ctn3.copy()
df_ctn34 = df_ctn3.copy()
df_ctn31['cast'] = df_ctn31['cast'].astype(str).apply(lambda x: x.split('|')[0])
df_ctn32['cast'] = df_ctn32['cast'].astype(str).apply(lambda x: x.split('|')[1])
df_ctn33['cast'] = df_ctn33['cast'].astype(str).apply(lambda x: x.split('|')[2])
df_ctn34['cast'] = df_ctn34['cast'].astype(str).apply(lambda x: x.split('|')[3])
df_plus3 =df_ctn31.append(df_ctn32).append(df_ctn33).append(df_ctn34)

In [25]:
df_ctn4 = df.query('cast_counts == 4')
df_ctn41 = df_ctn4.copy()
df_ctn42 = df_ctn4.copy()
df_ctn43 = df_ctn4.copy()
df_ctn44 = df_ctn4.copy()
df_ctn45 = df_ctn4.copy()
df_ctn41['cast'] = df_ctn41['cast'].astype(str).apply(lambda x: x.split('|')[0])
df_ctn42['cast'] = df_ctn42['cast'].astype(str).apply(lambda x: x.split('|')[1])
df_ctn43['cast'] = df_ctn43['cast'].astype(str).apply(lambda x: x.split('|')[2])
df_ctn44['cast'] = df_ctn44['cast'].astype(str).apply(lambda x: x.split('|')[3])
df_ctn45['cast'] = df_ctn45['cast'].astype(str).apply(lambda x: x.split('|')[4])
df_plus4 =df_ctn41.append(df_ctn42).append(df_ctn43).append(df_ctn44).append(df_ctn45)

In [30]:
df = df_plus0.append(df_plus1,ignore_index = True).append(df_plus2,ignore_index = True).append(df_plus3,ignore_index = True).append(df_plus4,ignore_index = True)
df.shape

(52649, 12)

In [31]:
df.head(1)

,original_title,cast,director,keywords,runtime,genres,production_companies,release_date,vote_count,vote_average,profit,cast_counts
0,Ronaldo,Cristiano Ronaldo,Anthony Wonke,biography|soccer player,0,Documentary,"On The Corner Films|We Came, We Saw, We Conque...",11/9/15,80,6.5,0.0,0

In [32]:
df_plus4.groupby('original_title').count()

,cast,director,keywords,runtime,genres,production_companies,release_date,vote_count,vote_average,profit,cast_counts
original_title,,,,,,,,,,,
$5 a Day,5,5,5,5,5,5,5,5,5,5,5
$9.99,5,5,5,5,5,5,5,5,5,5,5
'71,5,5,5,5,5,5,5,5,5,5,5
(500) Days of Summer,5,5,5,5,5,5,5,5,5,5,5
(T)Raumschiff Surprise - Periode 1,5,5,5,5,5,5,5,5,5,5,5
*batteries not included,5,5,5,5,5,5,5,5,5,5,5
...And Justice for All,5,5,5,5,5,5,5,5,5,5,5
1,10,10,10,10,10,10,10,10,10,10,10
10,5,5,5,5,5,5,5,5,5,5,5
10 Items or Less,5,5,5,5,5,5,5,5,5,5,5
10 Rillington Place,5,5,5,5,5,5,5,5,5,5,5
10 Things I Hate About You,5,5,5,5,5,5,5,5,5,5,5
10 Years,5,5,5,5,5,5,5,5,5,5,5
"10,000 BC",5,5,5,5,5,5,5,5,5,5,5
10.5: Apocalypse,5,5,5,5,5,5,5,5,5,5,5
100 Bloody Acres,5,5,5,5,5,5,5,5,5,5,5
100 Degrees Below Zero,5,5,5,5,5,5,5,5,5,5,5
100 Feet,5,5,5,5,5,5,5,5,5,5,5
100 Girls,5,5,5,5,5,5,5,5,5,5,5
100% Cachemire,5,5,5,5,5,5,5,5,5,5,5
101 Dalmatians,5,5,5,5,5,5,5,5,5,5,5
101 Dalmatians II: Patch's London Adventure,5,5,5,5,5,5,5,5,5,5,5
102 Dalmatians,5,5,5,5,5,5,5,5,5,5,5
10th & Wolf,5,5,5,5,5,5,5,5,5,5,5
11/11/11,5,5,5,5,5,5,5,5,5,5,5
11:14,5,5,5,5,5,5,5,5,5,5,5
12 Angry Men,5,5,5,5,5,5,5,5,5,5,5
12 Men of Christmas,5,5,5,5,5,5,5,5,5,5,5
12 Rounds,5,5,5,5,5,5,5,5,5,5,5
12 Rounds 2: Reloaded,5,5,5,5,5,5,5,5,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...
Î¤Î± Ï€Î±Î¹Î´Î¹Î¬ Ï„Î¿Ï… Î´Î¹Î±Î²ÏŒÎ»Î¿Ï…,5,5,5,5,5,5,5,5,5,5,5
Ð¡Ñ‚Ð°Ð»Ð¸Ð½Ð³Ñ€Ð°Ð´,5,5,5,5,5,5,5,5,5,5,5
ÐÐ´Ð¼Ð¸Ñ€Ð°Ð»ÑŠ,5,5,5,5,5,5,5,5,5,5,5
Ð‘Ñ€Ð°Ñ‚ 2,5,5,5,5,5,5,5,5,5,5,5
×›×™×“×•×Ÿ,5,5,5,5,5,5,5,5,5,5,5
à¸ªà¸´à¹ˆà¸‡à¹€à¸¥à¹‡à¸à¹€à¸¥à¹‡à¸à¸—à¸µà¹ˆà¹€à¸£à¸µà¸¢à¸à¸§à¹ˆà¸²...à¸£à¸±à¸,5,5,5,5,5,5,5,5,5,5,5
à¸•à¹‰à¸¡à¸¢à¸³à¸à¸¸à¹‰à¸‡ 2,5,5,5,5,5,5,5,5,5,5,5
ã‚¢ãƒƒãƒ—ãƒ«ã‚·ãƒ¼ãƒ‰,5,5,5,5,5,5,5,5,5,5,5
ã‚´ã‚¸ãƒ©vsã‚¹ãƒšãƒ¼ã‚¹ã‚´ã‚¸ãƒ©,5,5,5,5,5,5,5,5,5,5,5
å¤ªæžå¼ ä¸‰ä¸°,5,5,5,5,5,5,5,5,5,5,5
å¸«å¼Ÿå‡ºé¦¬,5,5,5,5,5,5,5,5,5,5,5
æ±äº¬æ®‹é…·è­¦å¯Ÿ,5,5,5,5,5,5,5,5,5,5,5
æˆé¾çš„ç‰¹æŠ€,5,5,5,5,5,5,5,5,5,5,5
æ’•ç¥¨é¢¨é›²,5,5,5,5,5,5,5,5,5,5,5
ç­‰ä¸€å€‹äººå’–å•¡,5,5,5,5,5,5,5,5,5,5,5
ç»™çˆ¸çˆ¸çš„ä¿¡,5,5,5,5,5,5,5,5,5,5,5
è§£æ•‘å´å…ˆç”Ÿ,5,5,5,5,5,5,5,5,5,5,5
è³½å¾·å…‹Â·å·´èŠ (ä¸Š) å¤ªé™½æ——,5,5,5,5,5,5,5,5,5,5,5
è‰‹èˆº,5,5,5,5,5,5,5,5,5,5,5
é»‘ç¤¾ä¼š2ï¼šä»¥å’Œä¸ºè´µ,5,5,5,5,5,5,5,5,5,5,5
é€ƒå­¦å¨é¾™,5,5,5,5,5,5,5,5,5,5,5
ê³ ì‚¬ ë‘ ë²ˆì§¸ ì´ì•¼ê¸°: êµìƒì‹¤ìŠµ,5,5,5,5,5,5,5,5,5,5,5
ëª½íƒ€ì£¼,5,5,5,5,5,5,5,5,5,5,5
ì§íŒ¨,5,5,5,5,5,5,5,5,5,5,5
ì§‘ìœ¼ë¡œ ê°€ëŠ” ê¸¸,5,5,5,5,5,5,5,5,5,5,5
ìºì¹˜ë¯¸,5,5,5,5,5,5,5,5,5,5,5
ìž‘ì—…ì˜ ì •ì„,5,5,5,5,5,5,5,5,5,5,5
ì‹ ì˜ í•œ ìˆ˜,5,5,5,5,5,5,5,5,5,5,5
í¬í™” ì†ìœ¼ë¡œ,5,5,5,5,5,5,5,5,5,5,5
í˜•ì‚¬ Duelist,5,5,5,5,5,5,5,5,5,5,5

In [33]:
df['release_date'].isnull().sum()

0

In [35]:
df['month']=df['release_date'].apply(lambda x: x.split('/')[0]) #提取上映月份，并放入新列month中
df.head(3)

,original_title,cast,director,keywords,runtime,genres,production_companies,release_date,vote_count,vote_average,profit,cast_counts,month
0,Ronaldo,Cristiano Ronaldo,Anthony Wonke,biography|soccer player,0,Documentary,"On The Corner Films|We Came, We Saw, We Conque...",11/9/15,80,6.5,0.000000e+00,0,11
1,Monkey Kingdom,Tina Fey,Mark Linfield|Alastair Fothergill,,81,Animation|Documentary,Disneynature,4/17/15,39,6.3,1.532818e+07,0,4
2,Sanjay's Super Team,,Sanjay Patel,,7,Animation,Pixar Animation Studios,11/25/15,47,6.9,0.000000e+00,0,11

In [40]:
total_genres_rows = df['genres'].shape[0]
#计算genres一栏中，每个元素里含有几个”|“
genres_counts = []
for i in range(total_genres_rows):
    num_1 = df['genres'].astype(str).iloc[i].count('|')
    genres_counts.append(num_1)

In [41]:
set(genres_counts)

{0, 1, 2, 3, 4}

In [42]:
df['genres_counts'] = genres_counts  #添加一列genres_counts，表示genres中有几个|

In [43]:
df.head(2)

,original_title,cast,director,keywords,runtime,genres,production_companies,release_date,vote_count,vote_average,profit,cast_counts,month,genres_counts
0,Ronaldo,Cristiano Ronaldo,Anthony Wonke,biography|soccer player,0,Documentary,"On The Corner Films|We Came, We Saw, We Conque...",11/9/15,80,6.5,0.000000e+00,0,11,0
1,Monkey Kingdom,Tina Fey,Mark Linfield|Alastair Fothergill,,81,Animation|Documentary,Disneynature,4/17/15,39,6.3,1.532818e+07,0,4,1

In [45]:
df_ctn_0 = df.query('genres_counts == 0')
df_plus_0 = df_ctn_0

In [46]:
df_ctn_1 = df.query('genres_counts == 1')
df_ctn1_1 = df_ctn_1.copy()
df_ctn1_2 = df_ctn_1.copy()
df_ctn1_1['genres'] = df_ctn1_1['genres'].astype(str).apply(lambda x: x.split('|')[0])
df_ctn1_2['genres'] = df_ctn1_2['genres'].astype(str).apply(lambda x: x.split('|')[1])
df_plus_1 =df_ctn1_1.append(df_ctn1_2)

In [47]:
df_ctn_2 = df.query('genres_counts == 2')
df_ctn2_1 = df_ctn_2.copy()
df_ctn2_2 = df_ctn_2.copy()
df_ctn2_3 = df_ctn_2.copy()
df_ctn2_1['genres'] = df_ctn2_1['genres'].astype(str).apply(lambda x: x.split('|')[0])
df_ctn2_2['genres'] = df_ctn2_2['genres'].astype(str).apply(lambda x: x.split('|')[1])
df_ctn2_3['genres'] = df_ctn2_3['genres'].astype(str).apply(lambda x: x.split('|')[2])
df_plus_2 =df_ctn2_1.append(df_ctn2_2).append(df_ctn2_3)

In [48]:
df_ctn_3 = df.query('genres_counts == 3')
df_ctn3_1 = df_ctn_3.copy()
df_ctn3_2 = df_ctn_3.copy()
df_ctn3_3 = df_ctn_3.copy()
df_ctn3_4 = df_ctn_3.copy()
df_ctn3_1['genres'] = df_ctn3_1['genres'].astype(str).apply(lambda x: x.split('|')[0])
df_ctn3_2['genres'] = df_ctn3_2['genres'].astype(str).apply(lambda x: x.split('|')[1])
df_ctn3_3['genres'] = df_ctn3_3['genres'].astype(str).apply(lambda x: x.split('|')[2])
df_ctn3_4['genres'] = df_ctn3_4['genres'].astype(str).apply(lambda x: x.split('|')[3])
df_plus_3 =df_ctn3_1.append(df_ctn3_2).append(df_ctn3_3).append(df_ctn3_4)

In [49]:
df_ctn_4 = df.query('genres_counts == 4')
df_ctn4_1 = df_ctn_4.copy()
df_ctn4_2 = df_ctn_4.copy()
df_ctn4_3 = df_ctn_4.copy()
df_ctn4_4 = df_ctn_4.copy()
df_ctn4_5 = df_ctn_4.copy()
df_ctn4_1['genres'] = df_ctn4_1['genres'].astype(str).apply(lambda x: x.split('|')[0])
df_ctn4_2['genres'] = df_ctn4_2['genres'].astype(str).apply(lambda x: x.split('|')[1])
df_ctn4_3['genres'] = df_ctn4_3['genres'].astype(str).apply(lambda x: x.split('|')[2])
df_ctn4_4['genres'] = df_ctn4_4['genres'].astype(str).apply(lambda x: x.split('|')[3])
df_ctn4_5['genres'] = df_ctn4_5['genres'].astype(str).apply(lambda x: x.split('|')[4])
df_plus_4 =df_ctn4_1.append(df_ctn4_2).append(df_ctn4_3).append(df_ctn4_4).append(df_ctn4_5)

In [54]:
df = df_plus_0.append(df_plus_1,ignore_index = True).append(df_plus_2,ignore_index = True).append(df_plus_3,ignore_index = True).append(df_plus_4,ignore_index = True)
df.shape

(131879, 14)

In [58]:
df.head(2)

,original_title,cast,director,keywords,runtime,genres,production_companies,release_date,vote_count,vote_average,profit,cast_counts,month,genres_counts
0,Ronaldo,Cristiano Ronaldo,Anthony Wonke,biography|soccer player,0,Documentary,"On The Corner Films|We Came, We Saw, We Conque...",11/9/15,80,6.5,0.0,0,11,0
1,Sanjay's Super Team,,Sanjay Patel,,7,Animation,Pixar Animation Studios,11/25/15,47,6.9,0.0,0,11,0

In [61]:
df = df.drop(['cast_counts','genres_counts'],axis=1)
df.head(2)

,original_title,cast,director,keywords,runtime,genres,production_companies,release_date,vote_count,vote_average,profit,month
0,Ronaldo,Cristiano Ronaldo,Anthony Wonke,biography|soccer player,0,Documentary,"On The Corner Films|We Came, We Saw, We Conque...",11/9/15,80,6.5,0.0,11
1,Sanjay's Super Team,,Sanjay Patel,,7,Animation,Pixar Animation Studios,11/25/15,47,6.9,0.0,11

In [62]:
df.shape

(131879, 12)

In [ ]:
# #计算导演一栏中，每个元素里还有几个”|“
# director_counts = []
# for i in range(df_clean.shape[0]):
#     num_2 = df_clean['director'].astype(str).iloc[i].count('|')
#     director_counts.append(num_2)

In [ ]:
# set(director_counts)

In [117]:
# df_dir = df_clean[df_clean['director'].str.contains('|')]
# df_dir0 = df_dir.copy()
# df_dir1 = df_dir.copy()

In [118]:
# df_dir0.head(1)

,original_title,cast,director,keywords,runtime,genres,production_companies,release_date,vote_count,vote_average,profit,cast_counts,month
0,Ronaldo,Cristiano Ronaldo,Anthony Wonke,biography|soccer player,0,Documentary,"On The Corner Films|We Came, We Saw, We Conque...",11/9/15,80,6.5,0.0,0,11

In [119]:
# df_dir0['director'] = df_dir0['director'].apply(lambda x:x.split('|')[0])
# df_dir1['director']  = df_dir1['director'].apply(lambda x:x.split('|')[1])

IndexError: list index out of range

In [74]:
df_ctn = df[df['cast'].str.contains("|")]

In [86]:
df1 = df_ctn.copy()
df2 = df_ctn.copy()
df3 = df_ctn.copy()
df4 = df_ctn.copy()
df5 = df_ctn.copy()

In [97]:
#每个元素以”|“隔开并形成新的行
for i in cast_counts:
    new_rows = pd.DataFrame(columns = ['original_title', 'cast', 'director', 'keywords', 'runtime', 'genres',
                         'production_companies', 'release_date', 'vote_count', 'vote_average','profit'])
    df_plus = pd.DataFrame(columns = ['original_title', 'cast', 'director', 'keywords', 'runtime', 'genres',
                         'production_companies', 'release_date', 'vote_count', 'vote_average','profit'])
    if i ==0:
        df1[c] = df1[c].astype(str).apply(lambda x: x.split('|')[0])
        df_plus = df1
    if i == 1:
        df1[c] = df1[c].astype(str).apply(lambda x: x.split('|')[0])
        df2[c] = df2[c].astype(str).apply(lambda x: x.split('|')[1])
        df_plus =df1.append(df2)
    elif i == 2:
        df1[c] = df1[c].astype(str).apply(lambda x: x.split('|')[0])
        df2[c] = df2[c].astype(str).apply(lambda x: x.split('|')[1])
        df3[c] = df3[c].astype(str).apply(lambda x: x.split('|')[2])
        df_plus =df1.append(df2).append(df3)
    elif i == 3:
        df1[c] = df1[c].astype(str).apply(lambda x: x.split('|')[0])
        df2[c] = df2[c].astype(str).apply(lambda x: x.split('|')[1])
        df3[c] = df3[c].astype(str).apply(lambda x: x.split('|')[2])
        df4[c] = df4[c].astype(str).apply(lambda x: x.split('|')[3])
        df_plus =df1.append(df2).append(df3).append(df4)
    elif i == 4:
        df1[c] = df1[c].astype(str).apply(lambda x: x.split('|')[0])
        df2[c] = df2[c].astype(str).apply(lambda x: x.split('|')[1])
        df3[c] = df3[c].astype(str).apply(lambda x: x.split('|')[2])
        df4[c] = df4[c].astype(str).apply(lambda x: x.split('|')[3])
        df5[c] = df5[c].astype(str).apply(lambda x: x.split('|')[4])
        df_plus = df1.append(df2).append(df3).append(df4).append(df5)
    
    new_rows.append(df_plus)
df = df.append(new_rows, ignore_index =True)

NameError: name 'c' is not defined

In [96]:
df.head()

,original_title,cast,director,keywords,runtime,genres,production_companies,release_date,vote_count,vote_average,profit
0,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,monster|dna|tyrannosaurus rex|velociraptor|island,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/15,5562,6.5,1.254446e+09
1,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,George Miller,future|chase|post-apocalyptic|dystopia|australia,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/15,6185,7.1,2.101614e+08
2,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,Robert Schwentke,based on novel|revolution|dystopia|sequel|dyst...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/15,2480,6.3,1.704191e+08
3,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,android|spaceship|jedi|space opera|3d,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/15,5292,7.5,1.718723e+09
4,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,car race|speed|revenge|suspense|car,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/15,2947,7.3,1.210949e+09

In [112]:
for c in split_columns:
    for i in df[c].iloc[range(total_rows)].count('|'):
        if i ==0:
            df1[c] = df1[c].astype(str).apply(lambda x: x.split('|')[0])
        if i == 1:
            df1[c] = df1[c].astype(str).apply(lambda x: x.split('|')[0])
            df2[c] = df2[c].astype(str).apply(lambda x: x.split('|')[1])
            
        elif i == 2:
            df1[c] = df1[c].astype(str).apply(lambda x: x.split('|')[0])
            df2[c] = df2[c].astype(str).apply(lambda x: x.split('|')[1])
            df3[c] = df3[c].astype(str).apply(lambda x: x.split('|')[2])
            
        elif i == 3:
            df1[c] = df1[c].astype(str).apply(lambda x: x.split('|')[0])
            df2[c] = df2[c].astype(str).apply(lambda x: x.split('|')[1])
            df3[c] = df3[c].astype(str).apply(lambda x: x.split('|')[2])
            df4[c] = df4[c].astype(str).apply(lambda x: x.split('|')[3])
            
        elif i == 4:
            df1[c] = df1[c].astype(str).apply(lambda x: x.split('|')[0])
            df2[c] = df2[c].astype(str).apply(lambda x: x.split('|')[1])
            df3[c] = df3[c].astype(str).apply(lambda x: x.split('|')[2])
            df4[c] = df4[c].astype(str).apply(lambda x: x.split('|')[3])
            df5[c] = df5[c].astype(str).apply(lambda x: x.split('|')[4])
#         else:
#             continue

KeyError: 'Level | must be same as name (None)'